project_id = "dkomihipebixlegygnoy"

[functions.stripe-adjust-payment-amount]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.send-photo-notification]
verify_jwt = false

[functions.test-photo-notification]
verify_jwt = false

[functions.auto-photo-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-customer-payment-methods]
verify_jwt = true

[functions.manual-authorize-booking]
verify_jwt = false

[functions.test-gabrielle-auth]
verify_jwt = false

[functions.manual-sync-payment-method]
verify_jwt = true

[functions.send-sms-notification]
verify_jwt = false

[functions.redirect-to-payment-collection]
verify_jwt = false
