project_id = "dkomihipebixlegygnoy"

[functions.send-payment-sms]
verify_jwt = false

[functions.process-sms-reminders]
verify_jwt = false

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.stripe-verify-payment-method]
verify_jwt = false

[functions.system-payment-action]
verify_jwt = false

[functions.stripe-adjust-payment-amount]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.send-photo-notification]
verify_jwt = false

[functions.test-photo-notification]
verify_jwt = false

[functions.auto-photo-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-customer-payment-methods]
verify_jwt = false

[functions.manual-authorize-booking]
verify_jwt = false

[functions.test-gabrielle-auth]
verify_jwt = false

[functions.manual-sync-payment-method]
verify_jwt = false

[functions.fix-stripe-customer-metadata]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.redirect-to-payment-collection]
verify_jwt = false

[functions.stripe-process-payments]
verify_jwt = false

[functions.stripe-authorize-payment]
verify_jwt = false

[functions.stripe-capture-payment]
verify_jwt = false

[functions.invoiless-get-customer]
verify_jwt = false

[functions.invoiless-create-customer]
verify_jwt = false

[functions.invoiless-create-send]
verify_jwt = false

[functions.stripe-get-payments]
verify_jwt = true

[functions.process-cleaning-photos]
verify_jwt = true

[functions.submit-job-application]
verify_jwt = false

[functions.track-funnel-event]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.send-bank-transfer-sms]
verify_jwt = false

[functions.send-admin-quote-email]
verify_jwt = false

[functions.seed-coverage-data]
verify_jwt = false
